[package]
name = "flowshop-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
# portable-simd = "0.4"

[profile.release]
opt-level = 3 # or 3 depending if you prefer size or speed
# codegen-units = 1
# lto = true
# panic = 'abort'
# strip = true
